# Generated by Django 3.0.4 on 2020-08-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='url')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('published', models.BooleanField()),
                ('sorting', models.ImageField(max_length=1, upload_to='', verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Uslusgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=70, null=True, unique=True, verbose_name='url')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('published', models.BooleanField(default='False', verbose_name='Публикация')),
                ('price', models.IntegerField(default='1', verbose_name='Цена')),
                ('sorting', models.ImageField(default='1', max_length=1, upload_to='', verbose_name='Сортировка')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uslugi.Category', verbose_name='Главная категория')),
                ('similar_services', models.ManyToManyField(null=True, related_name='_uslusgi_similar_services_+', to='uslugi.Uslusgi', verbose_name='Похожие услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
