# Generated by Django 3.0.4 on 2020-08-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='uslusgi',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sorting',
            field=models.IntegerField(default='1', max_length=1, null=True, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='uslusgi',
            name='sorting',
            field=models.IntegerField(default='1', max_length=1, null=True, verbose_name='Сортировка'),
        ),
    ]
