# Generated by Django 3.0.4 on 2020-08-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0002_auto_20200829_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uslusgi',
            name='similar_services',
            field=models.ManyToManyField(blank=True, null=True, related_name='_uslusgi_similar_services_+', to='uslugi.Uslusgi', verbose_name='Похожие услуги'),
        ),
    ]
