# Generated by Django 3.0.4 on 2020-09-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0005_auto_20200913_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank='null', default='images/no_photo/no_photo.png', null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
