# Generated by Django 3.0.8 on 2020-09-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0007_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='slug',
            field=models.URLField(max_length=70, unique=True, verbose_name='url'),
        ),
    ]
