# Generated by Django 3.0.8 on 2020-09-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0008_auto_20200915_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='slug',
            field=models.TextField(max_length=70, unique=True, verbose_name='url'),
        ),
    ]
