# Generated by Django 3.0.4 on 2020-09-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0009_auto_20200915_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='h1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок h1'),
        ),
        migrations.AddField(
            model_name='uslusgi',
            name='h1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок h1'),
        ),
    ]
