# Generated by Django 3.0.4 on 2020-10-03 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0010_auto_20200919_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=70, null=True, unique=True, verbose_name='url')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('h1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок h1')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='Контент страницы')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uslugi.Article', verbose_name='Основаная')),
            ],
        ),
    ]
