# Generated by Django 3.0.4 on 2020-11-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0012_article_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': True, 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=70, verbose_name='url'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='',
        ),
    ]
