# Generated by Django 3.0.4 on 2020-11-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0013_auto_20201104_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('comment', models.TextField(max_length=300, verbose_name='Комментарий')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('performer_lookup', 'Заявка взята в обработку'), ('cancelled', 'Заказ отменен'), ('delivered_finish', 'Заказ завершен')], default='new', max_length=30)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
